### ISSUE TITLE
등록 완료를 검증하는 api 구현

### ISSUE THREAD

**Issue by ghyeon0** [kookmin-sw/capstone-2020-19#15]
wear 앱에서 등록을 직접 할 수 없으므로 등록 완료 여부를 api 서버에서 알려주는 기능이 필요합니다.

요청 인자: 기기 앱 고유번호(uuid)

반환: {"status": 1/0, "register_result": 1/0} 의 형식으로 받을 수 있게 해주세요.

**Comment by younjae5** [comment]
class CheckID(Resource) 에 해당부분 기능 추가했습니다.
확인 부탁드립니다.

**Comment by ghyeon0** [comment]
검증 및 확인 완료
