### ISSUE TITLE
낙상감지 모델 예시 적용

### ISSUE THREAD

**Issue by SongJiYoung** [kookmin-sw/capstone-2020-19#9]
LSTM모델을 임시로 적용해본다.

**Comment by asteroid-612** [comment]
**예시 적용시에 series의 길이 하나를 어떻게 정해줘야하는가에 대하여 => 논의해야하는 상황**

**Comment by asteroid-612** [comment]
> **예시 적용시에 series의 길이 하나를 어떻게 정해줘야하는가에 대하여 => 논의해야하는 상황**

낙상 데이터의 길이에 맞추어 series의 길이를 30으로 적용. train / test 데이터셋 제작 완료.

**Comment by SongJiYoung** [comment]
정확도 98%로 모델 학습 완료
